### ISSUE TITLE
Weekly assignements not showing up.

### ISSUE THREAD

**Issue by KalyaSc** [0P3N50URC3-F0R3V3R/blackbeard#2] opened 2021-12-07 20:18 UTC
Hello !

First of all, thank you for everything you do/did ! Your hardwork and dedication !

I downloaded your latest version on cs ri*.** (DRG_S01P03_U35p3+GOLDBERGLAN+DDEMU) and followed up all instructions.
https://mega.nz/file/Q*/****

-certification file added to user and system
-on https://localhost/ I see the different files: weekly,deepdive,events,GlobalStateTime
-XAMPP Control Panel v3.3.0 (Compiled: Apr 6th 2021)
-I auto-generated seeds but also tried to manually enter seeds 
-I set an end date for every event
-Timer is active

Host file:
"IPv4 adress" services.ghostship.dk (I put my IPv4 adress without question marks)
"IPv4 adress" api.stathat.com (I put my IPv4 adress without question marks)

-I start the game with start_game.bat

Christmas, halloween and free beer events are working GREAT ! But there are no weekly assignments showing up :(. I don't know about deepdive because i'm level 12 !

Do you have any idea what's happening? 

Other useful information:
Windows 10

**Comment by KalyaSc** [comment] 2021-12-07 20:31
Hey :)

I just downloaded a save game where the user has a level 25 driller. And magically the weekly assignments and deep dives are showing up and working !

So it must be related to my save/steam id because when I put my personal save back, the weekly assignments are not showing up again :(

Do you have any idea? My Engineer is level 11 and my player rank is 5

**Comment by 0P3N50URC3-F0R3V3R** [comment] 2021-12-07 20:50
IDK if this is works in  a version of a save then it might be that if you reach the same level with your save it will work perhaps... I cannot debug this since it works for me... :\

**Comment by 0P3N50URC3-F0R3V3R** [comment] 2021-12-07 21:12
If you can check if you can use this thing beside Radmin... IDK if radmin lets to use ports 443 or 8443... :\

**Comment by 0P3N50URC3-F0R3V3R** [comment] 2021-12-07 21:24
Also you might need to advance the normal assignments to get weekly... :\

**Comment by edu8000** [comment] 2021-12-07 21:50
After searching in the steam forums and the wiki, I can confirm that weekly assignments won't show up until you're player rank 8, and you unlock another one when you first promote a dwarf, that's why it works with the other save.

**Comment by 0P3N50URC3-F0R3V3R** [comment] 2021-12-07 21:53
Yep that is true, you need to be LVL8... not the red the blue one :D But i wrote this on the cs.*** forums :D 
I thought that you are level 8 at the blue rank and the assignments not working, that is a problem...

As for the main events: I have no clue :\

**Comment by 0P3N50URC3-F0R3V3R** [comment] 2021-12-07 22:08
I am closing this topic, the Final conclusion:
Weekly assignments will show up as you are advancing to miner level 8 (The blue rank not the Red one.)

**Closed** 2021-12-07 22:08 UTC

**Comment by KalyaSc** [comment] 2021-12-07 22:45
Thank you :) Its working ! I tought it was level 8 miner ! Nice job !
